### ISSUE TITLE
CI/CD - part 1

### ISSUE THREAD

**Issue by davidnixon** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#161]
https://en.wikipedia.org/wiki/CI/CD

https://www.ibm.com/cloud/architecture/tutorials/introduce-develop-cloud-foundry-app-toolchain

- [ ] Understand the above documentation
- [ ] Deploy a new version of the UI part of this code to ibm cloud
    This will need a new manifest file like this:
    ```yaml
    ---
    applications:
      - name: fivefifthsvoter-preprod
        random-route: true
        memory: 512M
        buildpacks:
          - https://github.com/cloudfoundry/nginx-buildpack
    ```
    Using that manifest with proper credentials, a cf push from the `ui` dir will create a new app in the cloud foundry account.
    `cf push -f preprod.yml`
- [ ] Create a new toolchain for `fivefifthsvoter-preprod`
  Unlike the tutorial above I think you should start with an empty toolchain instead of starting with a pattern. That will allow you to use this existing github as the source instead of cloning this repo into IBM cloud github.
    ![image](https://user-images.githubusercontent.com/7536103/123482115-bf0bc480-d5d2-11eb-9918-cfc3f6f6a984.png)
  I also suggest you trigger a new build based on updates to a branch. I suggest a branch named "preprod"
  @upkarlidder may have a different suggestions
- [ ] Test the build/deploy by triggering manually and by triggering with a change to the "preprod" branch.
   

Next steps to be documented in other issues:
- repeat above steps for a new `fivefifthsvoter-services-preprod`
- attach the new services preprod to needed services (cloudant etc.)
- attach the preprod ui to the url for `fivefifthsvoter-services-preprod`
- attach the toolchain steps such that build ui -> build services -> deploy service -> deploy ui
- more steps here :-)
