### ISSUE TITLE
Add automatic deployment to blue server

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Five-Fifths-Voter#272]
### Background on the problem the feature will solve/improved user experience
Add GitHub actions to deploy solution to blue site whenever code is pushed to the blue branch. The action will first call `build-ui`, `build-services` and any other actions needed for successful build.

### Describe the solution you'd like
Create an action that deploys the ui and services components to the cloud using cloud foundry

### Tasks 
@davidnixon I am testing in a more simplistic [sample repo](https://github.com/upkarlidder/ci-cd-node-delete) and this works well

.github/workflows/deploy-blue-cf.yml
```
name: Deploy Blue CF

on:
  push:
    branches:
    - blue
  pull_request:
    branches:
    - blue

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to IBM Cloud Foundry
        # You may pin to the exact commit or the version.
        uses: IBM/cloudfoundry-deploy@master
        with:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          IBM_CLOUD_CF_API: ${{ secrets.IBM_CLOUD_CF_API }}
          IBM_CLOUD_CF_ORG: ${{ secrets.IBM_CLOUD_CF_ORG }}
          IBM_CLOUD_CF_SPACE: ${{ secrets.IBM_CLOUD_CF_SPACE }}
          APP_VARS_FILE: ${{ secrets.APP_VARS_FILE }}
```

blue.yml (customize build for the blue environment)
```
name: cicdnodedelete-blue
memory: 64M
```

manifest.yml (adding variables that will be picked up from blue.yml)
@davidnixon this is problematic as you will have to change the existing build perhaps? Can you create `production.yml` for vars and use that in tekton pipelines with the [--vars-file](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#-add-variables-to-a-manifest) argument? Alternatively I can just create `manifest-blue.yml` and not touch the existing manifest file. Learning more towards the latter. 
```
---
applications:
- instances: 1
  timeout: 180
  name: ((name))
  buildpack: nodejs_buildpack
  command: npm start
  random-route: true
  memory: ((memory))
  env:
    OPTIMIZE_MEMORY: true
```

### Acceptance Criteria 
GitHub action that deploys to the blue server whenever code is pushed to the blue branch.
